[variables]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"

[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["NPM_CONFIG_PRODUCTION=false npm ci"]

[phases.build]
cmds = ["NPM_CONFIG_PRODUCTION=false npm run build"]

[start]
cmd = "npm start"
